### ISSUE TITLE
de: errcount.com is down - evil redirect

### ISSUE THREAD

**Issue by helium-software** [gitready/gitready#28]
This issue only happens on German pages (on [de.gitready.com](http://de.gitready.com)), not on English ones (other languages untested): **Any page loads but then redirects to http://errcount.com/**. 

The behaviour comes from the line `<script src="http://errcount.com/ctr/762.js"></script>` ... good news, the site hasn't been hacked but errcount.com seems not to exist anymore (the site showing up says: _This domain is for sale! Buy it now! Click Here_). Maybe find another counter service...

**Comment by qrush** [comment]
Yikes! I'll get this off gitready today. Thanks.

**Comment by micha149** [comment]
The german translation is stil not accessible… Is it a Problem to kick that script?

**Comment by qrush** [comment]
Fixed! Sorry about this stupidness, folks.
