### ISSUE TITLE
Broken internationalized url

### ISSUE THREAD

**Issue by stang** [gitready/gitready#54]
It seems that the different links used to access to the translated version — see: on the very bottom of the pages — are broken.

I suspect that the dns entries for de.gitready.com, fr.gitready.com, etc. are not declared in the public dns zone.

**Comment by ryansb** [comment]
Oh, so sorry!

I've fixed the records now, so http://fr.gitready.com/ should work now (or soon, as the records propagate). In the meantime you can find the French translation at https://gitready.github.io/fr/
